version: '3.8'

networks:
  spendsense-net:
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-1
    ports:
      - "5672:5672"  # RabbitMQ communication
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword
    networks:
      - spendsense-net


  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    environment:
      OAUTH2_PROXY_PROVIDER: "keycloak"
      OAUTH2_PROXY_CLIENT_ID: "spendsense-client"          # The Keycloak client ID you just created
      OAUTH2_PROXY_CLIENT_SECRET: "rHY2zaYVS94C3TFCUEa5VEsryd90J7xQ"     # The Keycloak client secret you copied
      OAUTH2_PROXY_COOKIE_SECRET: "P0vDq32mpPl5AVv0YQ4hlmv2EO5ylAMOehDN0I7eF7Q="         # Should be a random string (e.g., base64-encoded)
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"                      # Allow all email domains
      OAUTH2_PROXY_REDIRECT_URL: "http://localhost/oauth2/callback"  # URL to handle the callback from Keycloak
      OAUTH2_PROXY_UPSTREAMS: "http://expense-service:8080"  # Your backend service (e.g., budget-service)
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"          # Port for the proxy to listen on
      OAUTH2_PROXY_COOKIE_SECURE: "false"                  # Disable cookie security in dev (change to true in prod)
      OAUTH2_PROXY_INSECURE: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth2-proxy.rule=Host(`localhost`)"
      - "traefik.http.services.oauth2-proxy.loadbalancer.server.port=4180"
    ports:
      - "4180:4180"
    networks:
      - spendsense-net
    depends_on:
      - keycloak

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik Dashboard
      - "443:443"    # HTTPS (optional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - spendsense-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oauth2.rule=Host(`localhost`) && PathPrefix(`/oauth2/`)"
      - "traefik.http.routers.oauth2.entrypoints=web"
      - "traefik.http.routers.oauth2.service=oauth2-proxy"
      - "traefik.http.services.oauth2-proxy.loadbalancer.server.port=4180"
      - "traefik.http.middlewares.oauth2-proxy-forwardauth.forwardauth.address=http://oauth2-proxy:4180/oauth2/auth"
      - "traefik.http.middlewares.oauth2-proxy-forwardauth.forwardauth.authResponseHeaders=X-Auth-Request-User,X-Auth-Request-Email"
      
  mysql-budget:
    image: mysql:latest
    container_name: mysql-budget-1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: budget_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - spendsense-net

  mysql-expenses:
    image: mysql:latest
    container_name: mysql-expense-1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expense_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - spendsense-net
  
  mysql-keycloak:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - spendsense-net
  
  budget-service:
    #image: budget-service
    build: ./budget-service/openjdk
    container_name: budget-service-1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.budget.rule=Host(`budget.localhost`)"
      - "traefik.http.services.budget.loadbalancer.server.port=8080"
    networks:
      - spendsense-net
    depends_on:
      - mysql-budget

  expense-service:
    #image: expense-service
    build: ./expense-service/openjdk
    container_name: expense-service-1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.expense.rule=Host(`expense.localhost`)"
      - "traefik.http.services.expense.loadbalancer.server.port=8080"
    networks:
      - spendsense-net
    depends_on:
      - mysql-expenses
   
  k6:
    image: grafana/k6
    container_name: k6-load-tester
    networks:
      - spendsense-net
    depends_on:
      - budget-service
      - expense-service
    volumes:
      - ./k6:/scripts:ro  # Mount a folder to store test scripts
    command: ["k6", "run", "/scripts/test.js"]
    
    
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql-keycloak
      KC_DB_URL_PORT: 3306
      #KC_DB_SCHEMA: public
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
    depends_on:
      - mysql-keycloak
    networks:
      - spendsense-net


 
volumes:
  mysql_data:

