entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls: {}  # Активира TLS за този entrypoint
      
  metrics:
    address: ":8082"

providers:
  docker:
    exposedByDefault: false  # За по-голяма сигурност

  file:
    filename: "/etc/traefik/dynamic_conf.yml"
    watch: true

api:
  insecure: true

log:
  level: DEBUG
  
metrics:
  prometheus:
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
