apiVersion: v1
kind: Secret
metadata:
  name: azure-servicebus-secret
  namespace: default
  labels:
    app: spendsense
    environment: production
type: Opaque
data:
  SERVICEBUS_CONNECTION_STRING: RW5kcG9pbnQ9c2I6Ly9zcGVuZHNlbnNlLXNlcnZpY2UtYnVzLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9Um9vdE1hbmFnZVNoYXJlZEFjY2Vzc0tleTtTaGFyZWRBY2Nlc3NLZXk9THpZUjlQQWExM05YbDNGN0VQcTk3UDVIVUh6Uk85TGxNK0FTYkRTYm0waz0=
  TOPIC_CONNECTION_STRING: RW5kcG9pbnQ9c2I6Ly9zcGVuZHNlbnNlLXRvcGljLnNlcnZpY2VidXMud2luZG93cy5uZXQvO1NoYXJlZEFjY2Vzc0tleU5hbWU9Um9vdE1hbmFnZVNoYXJlZEFjY2Vzc0tleTtTaGFyZWRBY2Nlc3NLZXk9allKU0I2Ly93YTZSelNNQXJRZFpyR1F4ZVg3Zm9Nc3Z1aCtBU2JHNGtPbWM9
#
# Replace <base64-encoded-connection-string> and <base64-encoded-topic-connection-string> with your actual values.
# Example (in PowerShell):
# [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("Endpoint=sb://...;SharedAccessKey=..."))
#
# Then, apply this secret with:
# kubectl apply -f infra/k8s/azure-secrets.yaml
