apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-service
spec:
  replicas: 1 # Adjust as needed
  selector:
    matchLabels:
      app: expense-service
  template:
    metadata:
      labels:
        app: expense-service
    spec:
      containers:
      - name: expense-service
        image: viktoria2003/services-expense-service:latest # <-- Updated image path
        imagePullPolicy: IfNotPresent # Or Always, if you want to ensure the latest is pulled
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8080 # Assuming your service runs on port 8080
        env:
        # Add any environment variables your expense-service needs
        # Example for database connection:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-expense-service:3306/expense_db?useSSL=false&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-expense-secret
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-expense-secret
              key: MYSQL_PASSWORD
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq-service
        # Add other necessary environment variables
---
apiVersion: v1
kind: Service
metadata:
  name: expense-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: expense-service
  type: ClusterIP # Will be exposed via Ingress