apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budgets-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/budgets/$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - app.spendsense.net
      secretName: spendsense-tls
  rules:
    - host: app.spendsense.net
      http:
        paths:
          - path: /budgets(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: budget-service
                port:
                  number: 80
          - path: /budgets/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: budget-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expenses-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/expenses$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:5173"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  tls:
    - hosts:
        - app.spendsense.net
      secretName: spendsense-tls
  rules:
    - host: app.spendsense.net
      http:
        paths:
          - path: /expenses(/.*)?
            pathType: ImplementationSpecific
            backend:
              service:
                name: expense-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: message-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/message/$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - app.spendsense.net
      secretName: spendsense-tls
  rules:
    - host: app.spendsense.net
      http:
        paths:
          - path: /api/message(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: spendsense-saga-user-delete-service
                port:
                  number: 80