global:
  scrape_interval: 15s
  
rule_files:
  - "/etc/prometheus/alert_rules.yml"

scrape_configs:
  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8082']
      
  - job_name: 'expense-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['expense-service:8080']
  
  - job_name: 'budget-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['budget-service:8080']
      
  - job_name: 'gdpr-orchestrator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gdpr-orchestrator:8080']