name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build budget-service JAR
        run: |
          cd Implementation/services/budget-service
          ./gradlew.bat build -x test
        shell: powershell

      - name: Build expense-service JAR
        run: |
          cd Implementation/services/expense-service
          ./gradlew.bat build -x test
        shell: powershell

      - name: Copy JARs to openjdk folders
        run: |
          Copy-Item Implementation/services/budget-service/build/libs/budget-service-0.0.1-SNAPSHOT.jar Implementation/services/budget-service/openjdk/
          Copy-Item Implementation/services/expense-service/build/libs/expense-service-0.0.1-SNAPSHOT.jar Implementation/services/expense-service/openjdk/
        shell: powershell

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          choco install docker-desktop --pre --confirm
          refreshenv
          docker-compose --version
        shell: powershell

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          choco install docker-desktop --pre --confirm
          refreshenv
          docker-compose --version
        shell: powershell

      - name: Start k6 container and run tests
        run: |
          docker-compose -f Implementation/services/docker-compose.yml up -d k6
        shell: powershell

